import Navbar from "./Components/Navbar";

export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Haarika's Creative Corner</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body>
                <header>
                    <Navbar />
                </header>
                <main>{children}</main>
            </body>
        </html>
    );
}