import Navbar from "./Components/Navbar";
import "bootstrap/dist/css/bootstrap.min.css";
export default function RootLayout({ children }) {
    return (
        <html lang="en">
            <head>
                <title>Haarika's Creative Corner</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </head>
            <body style={{
                backgroundColor: "#fbede6"
            }} >
                <header>
                    <Navbar />
                </header>
                <main>{children}</main>

                <footer>
                    <div className="pt-5 mt-5">
                        <h4 className="text-wrap px-5 py-3 d-flex align-items-flex-end justify-content-center">Get in Touch
                        </h4>
                        <ul>
                            <p className="px-4 d-flex justify-content-center">LinkedIn : https://www.linkedin.com/in/haarika-ramadugu/</p>
                            <p className="px-4 d-flex justify-content-center">Github: Haarika701</p>
                            <p className="px-4 d-flex justify-content-center">Email: hramadugu@gmail.com</p>

                        </ul>
                    </div>
                </footer >

            </body >
        </html >
    );
}